variables:
  AWS_DOCKER_REGISTRY: localhost
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
  CI_REGISTRY_USER: "CI_REGISTRY_USER"
  CI_REGISTRY_PASSWORD: "CI_REGISTRY_PASSWORD"
  CI_REGISTRY: localhost
  CI_REGISTRY_PATH: path
